### PR TITLE
Allow api to be used as a library as well

### PR DESCRIPTION
**Pull request by ZzAve**
Hi! I'm working on an integration of Free@Home with [Homey](https://www.athom.com/en/) here: https://github.com/ZzAve/de.buschjaeger.freeathome

My primary goal is to internalise this library, basically bypassing the ws and/or http interface and jacking in to the functionality of your library directly. 

My changes in include:
- Expose a `run` and `SystemAccessPoint` module in index.ts, allowing for `import {SystemAccessPoint} from freeathom-api` in dependents
- Intodruce a generic 'Subscriber' interface to have a definition of what subscrber should implement. 

I'm very happy with your work and I think you did a great job taking over from Stefan!

### CODE REVIEW

**Comment by henry-spanka** [comment]
Thanks. I also had that in mind. Some parts of the library are still a mess but it does what it's supposed to do.

The application class still needs to implement the Subscriber interface. Can you please add a commit for that?

Otherwise it looks good. If you like, you can add some documentation to the README on how to use the API as a library. Otherwise I'll do that in a week or so. My laptop is currently being repaired so I'm a bit limited.

**Comment by henry-spanka** [comment]
And we also need to export the Configuration class. I guess we need to refactor it first and add the ws/http options to a separate class.

**Comment by ZzAve** [comment]
Thanks for the quick and on-point review! I have noticed that error handling is still very much tightly connected to the Application class and running the api as a process. I tried some refactoring there.

I'll try to do something with the config as well, although for now I've been using the full config, which works as well (the http, ws, and debug part) aren't used yet.

**Comment by henry-spanka** [comment]
Thanks. I think we can get this merged. Can you please export the Configuration class in the `index.ts` file? Otherwise we can't use the library externally as we don't have access to the Configuration class which is mandatory.

**Comment by ZzAve** [comment]
This last commit should do the trick, exposing `ClientConfiguration`

**Comment by henry-spanka** [comment]
Many thanks, merged!

I think I will release an updated version next week when I have my laptop back.

**Pull request merged**
